CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE artists(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255),
	PRIMARY KEY(id)
);

CREATE TABLE albums(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	year YEAR(4),
	artist_id INT,
	PRIMARY KEY(id),
	FOREIGN KEY(artist_id)
	REFERENCES artists(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE songs(
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	length INT,
	genre VARCHAR(255),
	album_id INT,
	PRIMARY KEY(id),
	FOREIGN KEY(album_id)
	REFERENCES albums(id)
		ON UPDATE CASCADE
		ON DELETE SET NULL
);

CREATE TABLE playlists (
	id INT NOT NULL AUTO_INCREMENT,
	date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	user_id INT,
	PRIMARY KEY(id),
	FOREIGN KEY(user_id)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE SET NULL
);

CREATE TABLE playlist_song(
	id INT NOT NULL AUTO_INCREMENT,
	song_id INT,
	playlist_id INT,
	PRIMARY KEY(id),
	FOREIGN KEY(song_id)
		REFERENCES songs(id)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
	FOREIGN KEY(playlist_id)
		REFERENCES playlists(id)
		ON UPDATE CASCADE
		ON DELETE SET NULL
);

ALTER TABLE artists DROP COLUMN name;

ALTER TABLE artists ADD COLUMN name VARCHAR(255) NOT NULL;

-- To rename a table
ALTER TABLE <table name> RENAME TO <new table name>;

---------------------------------------------------------------


CREATE DATABASE b55IRS;

CREATE TABLE users(
id INT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
birthday DATE NOT NULL,
contactNo VARCHAR(11) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(32) NOT NULL,
PRIMARY KEY(id)
); 

CREATE TABLE categories(
id INT NOT NULL AUTO_INCREMENT,
type VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE priorities(
id INT NOT NULL AUTO_INCREMENT,
level VARCHAR(15) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE tickets(
id INT NOT NULL AUTO_INCREMENT,
user_id INT,
priority_id INT,
category_id INT,
PRIMARY KEY(id),
FOREIGN KEY(user_id)
REFERENCES users(id)
ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(priority_id)
REFERENCES priorities(id)
ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(category_id)
REFERENCES categories(id)
ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE items(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
description VARCHAR(255) NOT NULL,
date_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ticket_id INT,
user_id INT,
PRIMARY KEY(id),
FOREIGN KEY(ticket_id)
REFERENCES tickets(id)
ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(user_id)
REFERENCES users(id)
ON UPDATE CASCADE
ON DELETE SET NULL
);

